name: Example Workflow
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
  steps:
    with:
      java-version: 15
    - name: Checkout
      uses: actions/checkout@v2
    - uses: joschi/setup-jdk@v2.3.0
    - name: Build
      run: ./gradlew build
    
