name: Test on Linux
on:
  push: 
jobs:
  Build:
    runs-on: ubuntu-18.04
    env:
      TERM: dumb
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 15
      - name: Build
        run: ./gradlew clean build
      - name: Run
        run: ./gradlew run  
