on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: My_Checkout
        uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 15
      - name: Build
        run: ./gradlew build
    
